version: 1
release:
  # Branch configuration
  branch: main

  # Version bump type
  defaultBump: patch

  # Changelog configuration
  changelog:
    enabled: true
    template: conventional

  # Release actions actions
  actions:
    - type: custom
      name: "assembly"
      command: "make assembly"
    - type: commit-push
    - type: git-tag
    - type: github-release
