// This file is auto-generated by @hey-api/openapi-ts

export type StringSchema = string;

export type ObjectSchema2 = {
    name?: string;
    email?: string;
    age?: number;
};

export type ObjectSchema = {
    status?: string;
    timestamp?: number;
    service?: string;
    approach?: string;
};

export type ObjectSchema3 = {
    error?: string;
    message?: string;
    details?: Array<{
        [key: string]: unknown;
    }>;
};

export type ObjectSchema1 = {
    id?: string;
    name?: string;
    email?: string;
    age?: number;
};

export type ClientOptions = {
    baseUrl: 'http://0.0.0.0:8082' | (string & {});
};