// This file is auto-generated by @hey-api/openapi-ts

/**
 * CreateUserRequest
 * Request payload for creating a new user
 */
export type CreateUserRequest = {
    /**
     * Full name of the user
     */
    name: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Age in years
     */
    age: number;
    /**
     * Whether the user account should be active
     */
    isActive?: boolean;
};

/**
 * ErrorResponse
 * Error response with details
 */
export type ErrorResponse = {
    /**
     * Error type identifier
     */
    error: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Additional error details
     */
    details?: Array<string>;
};

/**
 * User
 * A user in the system
 */
export type User = {
    /**
     * Full name of the user
     */
    name: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Age in years
     */
    age: number;
    /**
     * Unique identifier for the user
     */
    id: string;
    /**
     * Whether the user account is active
     */
    isActive?: boolean;
};

/**
 * UserListResponse
 * Paginated list of users with metadata
 */
export type UserListResponse = {
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Total number of users matching filters
     */
    total: number;
    /**
     * Number of users per page
     */
    limit: number;
    /**
     * List of users for this page
     */
    users: Array<{
        /**
         * Full name of the user
         */
        name: string;
        /**
         * Email address
         */
        email: string;
        /**
         * Age in years
         */
        age: number;
        /**
         * Unique identifier for the user
         */
        id: string;
        /**
         * Whether the user account is active
         */
        isActive?: boolean;
    }>;
    /**
     * Current page number
     */
    page: number;
};

/**
 * UserListQuery
 * Query parameters for filtering and paginating users
 */
export type UserListQuery = {
    /**
     * Page number (1-based)
     */
    page?: number;
    /**
     * Number of users per page
     */
    limit?: number;
    /**
     * Filter by name (case-insensitive partial match)
     */
    search?: string;
    /**
     * Filter by active status
     */
    active?: boolean;
};

/**
 * SuccessResponse
 * Generic success response
 */
export type SuccessResponse = {
    /**
     * Success message
     */
    message: string;
};

/**
 * SuccessResponse
 * Generic success response
 */
export type SuccessResponse1 = {
    /**
     * Success message
     */
    message: string;
};

/**
 * UpdateUserRequest
 * Request payload for updating an existing user
 */
export type UpdateUserRequest = {
    /**
     * Full name of the user
     */
    name?: string;
    /**
     * Email address
     */
    email?: string;
    /**
     * Age in years
     */
    age?: number;
    /**
     * Whether the user account is active
     */
    isActive?: boolean;
};

export type ClientOptions = {
    baseUrl: 'http://0.0.0.0:8082' | (string & {});
};