// This file is auto-generated by @hey-api/openapi-ts

/**
 * UserListQuery
 * Query parameters for listing users
 */
export type UserListQuery = {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of users per page
     */
    limit?: number;
    /**
     * Search term for filtering users
     */
    search?: string;
};

/**
 * HealthResponse
 * Health check response
 */
export type HealthResponse = {
    /**
     * Health status
     */
    status: string;
    /**
     * Current timestamp
     */
    timestamp: number;
    /**
     * Service name
     */
    service: string;
    /**
     * Implementation approach
     */
    approach: string;
};

/**
 * UserQuery
 * Query parameters for user lookup
 */
export type UserQuery = {
    /**
     * Whether to include full user details
     */
    includeDetails?: boolean;
};

/**
 * CreateUserRequest
 * Request to create a new user
 */
export type CreateUserRequest = {
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The age of the user
     */
    age: number;
};

/**
 * HelloResponse
 * Simple hello message
 */
export type HelloResponse = {
    /**
     * The hello message
     */
    message: string;
};

/**
 * ErrorResponse
 * An error response
 */
export type ErrorResponse = {
    /**
     * The error message
     */
    error: string;
    /**
     * The error message
     */
    message: string;
    /**
     * The error details
     */
    details: Array<string>;
};

/**
 * User
 * A user
 */
export type User = {
    /**
     * The ID of the user
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The age of the user
     */
    age: number;
};

/**
 * UserListResponse
 * Paginated list of users
 */
export type UserListResponse = {
    /**
     * List of users
     */
    users: Array<{
        /**
         * The ID of the user
         */
        id: string;
        /**
         * The name of the user
         */
        name: string;
        /**
         * The email of the user
         */
        email: string;
        /**
         * The age of the user
         */
        age: number;
    }>;
    /**
     * Total number of users
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Users per page
     */
    limit: number;
};

export type ClientOptions = {
    baseUrl: 'http://0.0.0.0:8082' | (string & {});
};